repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: "v0.1.17" # Get the latest from: https://github.com/gruntwork-io/pre-commit/releases
    hooks:
      - id: tflint
        args:
          - --module
          - --enable-rule=terraform_documented_variables
          - --enable-rule=terraform_naming_convention
          - --config=.tflint.hcl
      - id: terragrunt-hclfmt
      - id: terraform-fmt

  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.16.0" # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
      - id: terraform-docs-go
        args: ["."]

  - repo: https://github.com/adrienverge/yamllint
    rev: "v1.26.3"
    hooks:
      - id: yamllint
