<?php $this->headTitle('Bid History'); ?>
<div class="jumbotron">
    <h1>Bidy dla: <?= $this->date; ?></h1>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Twitter User</th>
          <th scope="col">Bids</th>
          <th scope="col">MD5 Checksum</th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($this->rowset as $i => $row): ?>
         <tr>
            <th scope="row"><?= $i+1; ?></th>
            <td><?= $row['name']; ?></td>
            <td><pre><?= $row['bids']; ?></pre></td>
            <td><?= $row['checksum']; ?></td>
          </tr>
        </tbody>
        <?php endforeach; ?>
      </table>
      <a href="https://elmah.io/tools/md5-encoder/" target="_blank">Hash checker</a>
</div>