version: "2.1"

services:
  build:
    image: jacops/alpine-envsubst:latest
    entrypoint: []
    command: bin/build.sh
    environment:
      GA_CODE: "${GA_CODE}"
    working_dir: /workspace
    volumes:
      - .:/workspace

  aws-cli:
    image: amazon/aws-cli:latest
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
      - AWS_PROFILE
    working_dir: /workspace
    volumes:
      - .:/workspace
      - ~/.aws:/root/.aws

  deploy:
    extends:
      service: aws-cli
    entrypoint: []
    command: bin/deploy.sh -b ${DEPLOY_BUCKET_NAME}